General:
  UseMySQL: false
  MySQL:
    User: null
    Db: null
    Pass: null
    Host: null
  StartingPoints: 1000
Kills:
# Jesli zabity ma wiecej punktow niz zabijajacy to losowy procent z roznicy tej liczby zostanie dodany do konta zabijajacego.
# If killed have more points than killer then random % of (KilledPoints - KillerPoints) is added to killer.
  MinPercentage: 5
  MaxPercentage: 10
  
# Jesli zabity ma mniej niz tyle puktow to zabijajacy dostaje od "MinPoints" do "MaxPoints" i dodatkowo ma "PercentageToGetNegative"% ze te punkty zostana odjete zamiast dodane.
# If killed have less than NegativeWhen points then killer can get points between MinPoints and MaxPoints. But also have some % to get negative points.
  NegativeWhen: 1000
  MinPoints: 5
  MaxPoints: 15
  PercentageToGetNegative: 50
  
# Procent z liczby punktow ktora zdobyl zabijajacy jest odejmowana od konta zabitego.
# % from points gained by killer is subtracted from killed points
  LoseMinPercentage: 15
  LoseMaxPercentage: 28
  
# Jesli zabity ma mniej puktow niz zabijajacy to moze dostac od tylu do tylu pkt + pewien % szans ze pkt bd ujemne.
# if killed have less points than killer then can get points between MinPoints2 and MaxPoints2. But also have some % to get negative points.
  MinPoints2: 5
  MaxPoints2: 25
  PercentageToGetNegative2: 20
Messages:
# Sorry for polish default language!
# NoPermissions: '&4You don't have permissions to do that! You need: &9(&c{%Permission%}&9)'
  NoPermissions: '&4Nie masz permissions by to zrobic! &9(&c{%Permission%}&9)'
# OnKill: '&9Player: &4{%killer%} &9kill: &4{%killed%} &9{%lose/win%}: &a{%Vpoints%} &9p of ranking. &b(KD: &a{%Vkd%}&b)'
  OnKill: '&9Gracz: &4{%killer%} &9zabil: &4{%killed%} &9{%lose/win%}: &a{%Vpoints%} &9pkt rankingu. &b(KD: &a{%Vkd%}&b)'
# Lose: 'and lose'
  Lose: 'tracac'
# Win: 'and win'
  Win: 'zyskujac'
  TopListCmd:
# Points: 'points'
    Points: 'pkt'
# Kills: 'kills'
    Kills: 'zabicia'
# Deaths: 'deaths'
    Deaths: 'dedy'
    KD: 'kd'
  TopList:
    Top: '&e==============='
    Points: '&4{%pos%}. &9{%player%}&a || &b{%top%}'
    Kills: '&4{%pos%}. &9{%player%}&a || &b{%top%}'
    Deaths: '&4{%pos%}. &9{%player%}&a || &b{%top%}'
    KD: '&4{%pos%}. &9{%player%}&a || &b{%top%}'
    Bot: '&e==============='
# Stat: '&e===============\n&9Statistics of: &b{%player%}!\n&9Points: &b{%points%}\n&9Kills: &b{%kills%}\n&9Deaths: &b{%deaths%}\n&9KD: &b{%kd%}\n&e==============='
  Stat: '&e===============\n&9Statystyki gracza: &b{%player%}!\n&9Punkty: &b{%points%}\n&9Zabici: &b{%kills%}\n&9Smierci: &b{%deaths%}\n&9KD: &b{%kd%}\n&e==============='